using System;
using System.Collections;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using UnityEditor;
using Unity.VisualScripting;

public class UIManager : MonoBehaviour
{
    public static UIManager Instance;

    // Main Menu
    [SerializeField] Button quitMainMenu;                           // Quit button (Main Menu)

    // Menu How To Play
    [SerializeField] Button resumeHowToPlay;                        // Resume button (How To Play)

    // Menu Quit
    [SerializeField] Button cancelQuit;                             // Cancel button (Quit)
    [SerializeField] Button confirmQuit;                            // Confirm button (Quit)

    // End Game Menu
    [SerializeField] Button quitEndGame;                            // Quit button (End Game Menu)

    // Time's Up Menu
    [SerializeField] Button quitTimesUp;                            // Quit button (Time's Up Menu)

    // Menus
    [SerializeField] GameObject mainMenu;                           // Main Menu
    [SerializeField] GameObject howToPlayMenu;                      // How To Play Menu
    [SerializeField] GameObject quitMenu;                           // Quit Menu
    [SerializeField] GameObject gameUI;                             // Game UI
    [SerializeField] GameObject endGameMenu;                        // End Game Menu
    [SerializeField] GameObject timesUpMenu;                        // Time's Up Menu

    // Time for the menu activation
    [SerializeField] float timer = 5f;

    //// Variables generated by Unity
    //[SerializeField] GameObject UI;
    //[SerializeField] TextMeshProUGUI code;
    //bool done = true;

    //// Code generated by Unity
    //private void Update()
    //{
    //    if (code.text != "Code" && done)
    //    {
    //        UI.SetActive(false);
    //        done = false;
    //    }
    //}

    void Awake()
    {
        if (Instance == null)
        {
            Instance = this;
        }

        DontDestroyOnLoad(gameObject);
    }

    void Start()
    {
        // Hide all menus
        howToPlayMenu.SetActive(false);
        quitMenu.SetActive(false);
        gameUI.SetActive(false);
        endGameMenu.SetActive(false);
        timesUpMenu.SetActive(false);

        // Activates the Main Menu for few seconds
        StartCoroutine(TimerMainMenu());

        //startGame.onClick.AddListener(FakeStartGame);                   // Fake method for starting the game
        //startGame.onClick.AddListener(ToggleHowToPlayMenu);             // Activates How to play before starting the game

        //resumeHowToPlay.onClick.AddListener(ToggleHowToPlayMenu);

        quitMainMenu.onClick.AddListener(ToggleQuitMenu);                 // Calls Quit Game Menu (Main Menu)
        quitEndGame.onClick.AddListener(ToggleQuitMenu);                  // Calls Quit Game Menu (End Game Menu)
        quitTimesUp.onClick.AddListener(ToggleQuitMenu);                  // Calls Quit Game Menu (Time's Up Menu)

        // Quit Menu
        cancelQuit.onClick.AddListener(ToggleQuitMenu);
        confirmQuit.onClick.AddListener(ExitGame);
    }

    // Fake logic for starting the game
    public void FakeStartGame()
    {
        gameUI.SetActive(true);
        howToPlayMenu.SetActive(false);

        StartCoroutine(TimerHowToPlay());

        if (Input.GetKeyDown(KeyCode.Escape))   // Not working yet
        {
            ToggleQuitMenu();
        }
    }

    // Turn on and off the Quit Menu
    public void ToggleQuitMenu()
    {
        if (quitMenu.activeSelf == false)
        {
            quitMainMenu.interactable = false;
            quitMenu.SetActive(true);
        }
        else if (quitMenu.activeSelf == true)
        {
            quitMainMenu.interactable = true;
            quitMenu.SetActive(false);
        }
    }

    // Exit the application
    public void ExitGame()
    {
        Application.Quit();
    }

    // Timer for the Main Menu
    IEnumerator TimerMainMenu()
    {
        mainMenu.SetActive(true);                               // Activates the Main Menu
        yield return new WaitForSeconds(timer);                 // Sets the timer
        mainMenu.SetActive(false);                              // Deactivates
    }

    // Timer for How to Play
    IEnumerator TimerHowToPlay()
    {
        howToPlayMenu.SetActive(true);                          // Activates the How To Play Menu
        yield return new WaitForSeconds(timer);                 // Sets the timer
        howToPlayMenu.SetActive(false);                         // Deactivates
    }
}