using System;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using UnityEditor;
using Unity.VisualScripting;

public class UIManager : MonoBehaviour
{
    public static UIManager Instance;

    // Main Menu
    [SerializeField] Button startGame;                 // Start button
    [SerializeField] Button settings;                  // Settings button
    [SerializeField] Button quit;                      // Quit button

    // Menu Settings
    [SerializeField] Button backSettings;              // Back button (Settings)

    // Menu How To Play
    [SerializeField] Button resumeHowToPlay;           // Resume button (How To Play)

    // Menu Quit
    [SerializeField] Button cancelQuit;                // Cancel button (Quit)
    [SerializeField] Button confirmQuit;               // Confirm button (Quit)

    // Menus
    [SerializeField] GameObject mainMenu;              // Main Menu
    [SerializeField] GameObject settingsMenu;          // Settings Menu
    [SerializeField] GameObject howToPlayMenu;         // How To Play Menu
    [SerializeField] GameObject quitMenu;              // Quit Menu
    [SerializeField] GameObject gameUI;                // Game UI

    //// Variables generated by Unity
    //[SerializeField] GameObject UI;
    //[SerializeField] TextMeshProUGUI code;
    //bool done = true;

    //// Code generated by Unity
    //private void Update()
    //{
    //    if (code.text != "Code" && done)
    //    {
    //        UI.SetActive(false);
    //        done = false;
    //    }
    //}

    void Awake()
    {
        if (Instance == null)
        {
            Instance = this;
        }

        DontDestroyOnLoad(gameObject);
    }

    void Start()
    {
        // Hide all menus
        settingsMenu.SetActive(false);
        howToPlayMenu.SetActive(false);
        quitMenu.SetActive(false);
        gameUI.SetActive(false);

        //startGame.onClick.AddListener(FakeStartGame);                  // Fake method for starting the game

        settings.onClick.AddListener(ToggleSettingsMenu);
        backSettings.onClick.AddListener(ToggleSettingsMenu);

        startGame.onClick.AddListener(ToggleHowToPlayMenu);             // Activates How to play before starting the game
        resumeHowToPlay.onClick.AddListener(ToggleHowToPlayMenu);

        quit.onClick.AddListener(ToggleQuitMenu);
        cancelQuit.onClick.AddListener(ToggleQuitMenu);
        confirmQuit.onClick.AddListener(ExitGame);
    }

    // Fake logic for starting the game
    public void FakeStartGame()
    {
        gameUI.SetActive(true);
        howToPlayMenu.SetActive(false);

        if (Input.GetKeyDown(KeyCode.Escape))   // Not working yet
        {
            ToggleQuitMenu();
        }
    }

    // Turn on and off the Settings Menu
    public void ToggleSettingsMenu()
    {
        if (settingsMenu.activeSelf == false)
        {
            settings.interactable = false;
            startGame.interactable = false;
            quit.interactable = false;
            settingsMenu.SetActive(true);
        }
        else if (settingsMenu.activeSelf == true)
        {
            settings.interactable = true;
            startGame.interactable = true;
            quit.interactable = true;
            settingsMenu.SetActive(false);
        }
    }

    // Turn on and off the How To Play Menu
    public void ToggleHowToPlayMenu()
    {
        if (howToPlayMenu.activeSelf == false)
        {
            howToPlayMenu.SetActive(true);
            mainMenu.SetActive(false);
        }
        else if (howToPlayMenu.activeSelf == true)
        {
            howToPlayMenu.SetActive(false);
            FakeStartGame();
        }
    }

    // Turn on and off the Quit Menu
    public void ToggleQuitMenu()
    {
        if (quitMenu.activeSelf == false)
        {
            quit.interactable = false;
            settings.interactable = false;
            startGame.interactable = false;
            quitMenu.SetActive(true);
        }
        else if (quitMenu.activeSelf == true)
        {
            quit.interactable = true;
            settings.interactable = true;
            startGame.interactable = true;
            quitMenu.SetActive(false);
        }
    }

    // Exit the application
    public void ExitGame()
    {
        Application.Quit();
    }
}